#tls transport layer security
#mutuo, o cliente se autentica nos servidor e o servidor no cliente

server:
  port: 8080
#  ssl:
#    protocol: TLS
    #trust-store: classpath:keystore/trust.p12 #certificado do cliente
    #trust-store-password: abc123
    #client-auth: need #a autenticacao do cliente é obrigatoria
#    enabled: true
#    enabled-protocols:
#      - TLSv1.2
#    key-store-type: PKCS12
#    key-store: classpath:keystore/keystore.p12 #certificado do servidor
#    key-alias: test
#    key-store-password: abc123

spring:
  jmx:
    enabled: false
  config:
    location: classpath:/application.yml
  main:
    lazy-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: root
    driver-class-name: org.h2.Driver
  application:
    name: product
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/testdata
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true

logging:
  level:
    org.springframework.boot.autoconfigure: INFO