spring:
  jmx:
    enabled: false
  config:
    location: classpath:/application.yml
  main:
    lazy-initialization: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/product
    username: root
    password: root
  application:
    name: product
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/testdata
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true

logging:
  level:
    org.springframework.boot.autoconfigure: INFO