apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: fabricio211/product-service:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: http
  selector:
    app: product-service
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: product-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "product.example.com"
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: product-service-destination
spec:
  host: product-service
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: product-service-route
spec:
  hosts:
    - "product.example.com"
  gateways:
    - product-gateway
  http:
    - route:
        - destination:
            host: product-service
            port:
              number: 8080
      timeout: 1.5s
      fault:
        delay:
          percentage:
            value: 33
          fixedDelay: 3s