name: Commit Stage
on: push

env:
  REGISTRY: docker.io
  IMAGE_NAME: fabricio211/product-service
  VERSION: ${{ github.sha }}

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
  package:
    name: Package and Publish
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [ build ]
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
      security-events: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: Update values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'helm/values.yaml'
          propertyPath: 'tag'
          value: ${{ env.IMAGE_NAME }}
          commitChange: false
          updateFile: true
          token: ${{ secrets.GITHUB_TOKEN }}
          targetBranch: main
